import Head from 'next/head';

import { GraphQLClient, gql } from 'graphql-request';
import BlogCard from '../components/BlogCard';

const graphcms = new GraphQLClient('https://api-ap-south-1.hygraph.com/v2/cl774tuse0q9801ungd0k1zzb/master');

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Blog App By Nirav lathiya</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='container'>
          <div className='row'>
            {posts?.map((post) => {
              return (
                <>
                  <div className='col-lg-4'>
                    <BlogCard
                      title={post.title}
                      author={post.author}
                      coverPhoto={post.coverPhoto}
                      key={post.id}
                      datePublished={post.datePublished}
                      slug={post.slug}
                    />
                  </div>
                </>
              );
            })}
          </div>
        </div>
      </main>
    </div>
  );
}
